package org.assetsglobal.enums;

public enum BankingPartner {
	STATE_BANK_OF_INDIA,
	HDFC_BANK,
	ICICI_BANK,
	KOTAK_MAHINDRA_BANK,
	PUNJAB_NATIONAL_BANK,
	BANK_OF_BARODA,
	UNION_BANK_OF_INDIA,
	IDFC_FIRST_BANK,
	FEDERAL_BANK,BAJAJ_HOUSING_FINANCE,
	GODREJ_HOUSING_FINANCE
}
